export const speaker = [
  {
    speaker: 'mijin',
    display_name_ko: '미진',
    display_name_ja: 'ミジン',
    display_name_en: 'Mijin',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '잠시 안내방송 있겠습니다.',
    },
    tags_ko: ['차분한', '친절한', '감미로운', '친근한'],
    tags_ja: ['落ち着いた', '親切な', 'とろけるような', 'フレンドリーな'],
    tags_en: ['calm', 'kind', 'mellow', 'friendly'],
    tags_zh: ['冷静的', '亲切的', '美妙的', '和蔼的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:39:00+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'jinho',
    display_name_ko: '진호(jinho)',
    display_name_ja: 'ジンホ',
    display_name_en: 'Jinho',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '지금까지 네이버 뉴스에서 전해드렸습니다.',
    },
    tags_ko: ['신뢰가는', '활기찬', '싹싹한', '친절한'],
    tags_ja: ['信頼感を与える', '活気のある', '気さくな', '親切な'],
    tags_en: ['trustworthy', 'energetic', 'affable', 'kind'],
    tags_zh: ['可靠的', '有活力的', '善解人意的', '亲切的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:39:12+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'clara',
    display_name_ko: '클라라',
    display_name_ja: 'クララ',
    display_name_en: 'Clara',
    gender: 'F',
    lang: 'en',
    age_group: 'middle-aged and above',
    default_text: {
      '0': 'Hello, I am Clara.',
    },
    tags_ko: ['신뢰가는', '쓸쓸한', '차분한', '감미로운'],
    tags_ja: ['信頼感を与える', '寂しげな', '落ち着いた', 'とろけるような'],
    tags_en: ['trustworthy', 'lonely', 'calm', 'mellow'],
    tags_zh: ['可靠的', '孤单的', '冷静的', '美妙的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:39:21+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'matt',
    display_name_ko: '매트',
    display_name_ja: 'マット',
    display_name_en: 'Matt',
    gender: 'M',
    lang: 'en',
    age_group: 'youth',
    default_text: {
      '0': 'Hello, I am Matt.',
    },
    tags_ko: ['신뢰가는', '차분한', '친근한'],
    tags_ja: ['信頼感を与える', '落ち着いた', 'フレンドリーな'],
    tags_en: ['trustworthy', 'calm', 'friendly'],
    tags_zh: ['可靠的', '冷静的', '和蔼的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:39:30+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'shinji',
    display_name_ko: '캔지',
    display_name_ja: 'けんじ',
    display_name_en: 'Kenji',
    gender: 'M',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はケンジです。',
    },
    tags_ko: ['신뢰가는', '차분한', '매력적인', '감미로운'],
    tags_ja: ['信頼感を与える', '落ち着いた', '魅力的な', 'とろけるような'],
    tags_en: ['trustworthy', 'calm', 'charming', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '有魅力的', '美妙的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:39:40+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'meimei',
    display_name_ko: '메이메이',
    display_name_ja: 'メイメイ',
    display_name_en: 'Meimei    ',
    gender: 'F',
    lang: 'zh-CN',
    age_group: 'youth',
    default_text: {
      '0': '你好, 见到你很高兴。',
    },
    tags_ko: ['활기찬', '친절한', '사랑스러운'],
    tags_ja: ['活気のある', '親切な', 'ラブリーな'],
    tags_en: ['energetic', 'kind', 'lovely'],
    tags_zh: ['有活力的', '亲切的', '惹人喜爱的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:39:53+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'liangliang',
    display_name_ko: '량량',
    display_name_ja: 'リャンリャン',
    display_name_en: 'Liangliang',
    gender: 'M',
    lang: 'zh-CN',
    age_group: 'youth',
    default_text: {
      '0': '你好, 见到你很高兴。',
    },
    tags_ko: ['활기찬', '친근한', '속도감있는'],
    tags_ja: ['活気のある', 'フレンドリーな', 'スピード感のある'],
    tags_en: ['energetic', 'friendly', 'speedy'],
    tags_zh: ['有活力的', '和蔼的', '有速度感的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:40:09+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'jose',
    display_name_ko: '페르난도',
    display_name_ja: 'フェルナンド',
    display_name_en: 'Fernando',
    gender: 'M',
    lang: 'es',
    age_group: 'youth',
    default_text: {
      '0': 'Hola, mucho gusto.',
    },
    tags_ko: ['열정적인', '카리스마있는', '속도감있는'],
    tags_ja: ['情熱的な', 'カリスマ性のある', 'スピード感のある'],
    tags_en: ['passionate', 'charismatic', 'speedy'],
    tags_zh: ['热情的', '高冷的', '有速度感的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:40:45+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'carmen',
    display_name_ko: '카르멘',
    display_name_ja: 'カルメン',
    display_name_en: 'Carmen',
    gender: 'F',
    lang: 'es',
    age_group: 'youth',
    default_text: {
      '0': 'Hola, mucho gusto.',
    },
    tags_ko: ['신뢰가는', '카리스마있는', '속도감있는'],
    tags_ja: ['信頼感を与える', 'カリスマ性のある', 'スピード感のある'],
    tags_en: ['trustworthy', 'charismatic', 'speedy'],
    tags_zh: ['可靠的', '高冷的', '有速度感的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:40:58+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'nara',
    display_name_ko: '아라',
    display_name_ja: 'アラ',
    display_name_en: 'Ara',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '오늘도 소소한 일상 속에서, 행복을 찾는 즐거운 하루 되시길 바래요.',
      '1': '오늘은 컨디션이 별로 좋지 않네요.',
      '2': '그렇게 말씀해 주셔서 감사합니다.',
    },
    tags_ko: ['활기찬', '차분한', '매력적인', '친절한', '사랑스러운'],
    tags_ja: ['活気のある', '落ち着いた', '魅力的な', '親切な', 'ラブリーな'],
    tags_en: ['energetic', 'calm', 'charming', 'kind', 'lovely'],
    tags_zh: ['有活力的', '冷静的', '有魅力的', '亲切的', '惹人喜爱的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:41:21+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: true,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nsinu',
    display_name_ko: '신우',
    display_name_ja: 'シンウ',
    display_name_en: 'Shinwoo',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '철새들에게 먹이와 보금자리를 제공하는 천혜의 공간입니다.',
    },
    tags_ko: ['신뢰가는', '차분한', '싹싹한', '매력적인', '감미로운'],
    tags_ja: [
      '信頼感を与える',
      '落ち着いた',
      '気さくな',
      '魅力的な',
      'とろけるような',
    ],
    tags_en: ['trustworthy', 'calm', 'affable', 'charming', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '善解人意的', '有魅力的', '美妙的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:41:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njiyun',
    display_name_ko: '지윤',
    display_name_ja: 'ジユン',
    display_name_en: 'Jiyoon',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '저의 목소리를 들려드릴게요.',
    },
    tags_ko: ['신뢰가는', '친절한', '감미로운'],
    tags_ja: ['信頼感を与える', '親切な', 'とろけるような'],
    tags_en: ['trustworthy', 'kind', 'mellow'],
    tags_zh: ['可靠的', '亲切的', '美妙的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:41:57+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nsujin',
    display_name_ko: '수진',
    display_name_ja: 'スジン',
    display_name_en: 'Sujin',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '내일부터는 다시 맑은 날씨가 이어지겠습니다.',
    },
    tags_ko: ['신뢰가는', '차분한', '싹싹한'],
    tags_ja: ['信頼感を与える', '落ち着いた', '気さくな'],
    tags_en: ['trustworthy', 'calm', 'affable'],
    tags_zh: ['可靠的', '冷静的', '善解人意的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:42:17+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'ndain',
    display_name_ko: '다인',
    display_name_ja: 'ダイン',
    display_name_en: 'Dain',
    gender: 'F',
    lang: 'ko',
    age_group: 'child',
    default_text: {
      '0': '저 하늘에 있는 구름은 무슨 맛일까요?',
    },
    tags_ko: ['활기찬', '사랑스러운', '설레는', '호기심많은'],
    tags_ja: ['活気のある', 'ラブリーな', 'わくわくする', '好奇心旺盛な'],
    tags_en: ['energetic', 'lovely', 'heart-throbbing', 'curious'],
    tags_zh: ['有活力的', '惹人喜爱的', '令人心动的', '好奇心旺盛的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:42:35+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nhajun',
    display_name_ko: '하준',
    display_name_ja: 'ハジュン',
    display_name_en: 'Hajoon',
    gender: 'M',
    lang: 'ko',
    age_group: 'child',
    default_text: {
      '0': '저는 커서 과학자가 되고 싶어요!',
    },
    tags_ko: ['활기찬', '사랑스러운', '친근한', '금쪽같은', '호기심많은'],
    tags_ja: [
      '活気のある',
      'ラブリーな',
      'フレンドリーな',
      '大切な',
      '好奇心旺盛な',
    ],
    tags_en: ['energetic', 'lovely', 'friendly', 'precious', 'curious'],
    tags_zh: ['有活力的', '惹人喜爱的', '和蔼的', '洪亮的', '好奇心旺盛的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:42:46+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njihun',
    display_name_ko: '지훈',
    display_name_ja: 'ジフン',
    display_name_en: 'Jihoon',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '아래의 영상들은 허가없이 무단으로 사용하실 수 없습니다.',
    },
    tags_ko: ['신뢰가는', '차분한', '감미로운', '무뚝뚝한'],
    tags_ja: ['信頼感を与える', '落ち着いた', 'とろけるような', '無愛想な'],
    tags_en: ['trustworthy', 'calm', 'mellow', 'blunt'],
    tags_zh: ['可靠的', '冷静的', '美妙的', '沉默寡言的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:43:06+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njinho',
    display_name_ko: '진호(njinho)',
    display_name_ja: 'ジンホ',
    display_name_en: 'Jinho',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '지금까지 네이버 뉴스에서 전해드렸습니다.',
    },
    tags_ko: ['신뢰가는', '활기찬', '싹싹한', '친절한'],
    tags_ja: ['信頼感を与える', '活気のある', '気さくな', '親切な'],
    tags_en: ['trustworthy', 'energetic', 'affable', 'kind'],
    tags_zh: ['可靠的', '有活力的', '善解人意的', '亲切的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:43:10+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nminsang',
    display_name_ko: '민상',
    display_name_ja: 'ミンサン',
    display_name_en: 'Minsang',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '바람이 많이 부는 날이네요. 감기 조심하세요.',
    },
    tags_ko: ['신뢰가는', '차분한', '감미로운', '설레는', '저음의'],
    tags_ja: [
      '信頼感を与える',
      '落ち着いた',
      'とろけるような',
      'わくわくする',
      '低音の',
    ],
    tags_en: [
      'trustworthy',
      'calm',
      'mellow',
      'heart-throbbing',
      'low-pitched',
    ],
    tags_zh: ['可靠的', '冷静的', '美妙的', '令人心动的', '低音的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:43:21+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'ntaejin',
    display_name_ko: '태진',
    display_name_ja: 'テジン',
    display_name_en: 'Taejin',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '자연이 아름답기로 소문이 자자한 곳입니다.',
    },
    tags_ko: ['신뢰가는', '차분한', '감미로운'],
    tags_ja: ['信頼感を与える', '落ち着いた', 'とろけるような'],
    tags_en: ['trustworthy', 'calm', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '美妙的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:43:46+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'ngoeun',
    display_name_ko: '고은',
    display_name_ja: 'コウン',
    display_name_en: 'Koeun',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '오늘의 첫 곡은 비발디의 사계입니다.',
    },
    tags_ko: ['차분한', '친절한', '감미로운', '설레는'],
    tags_ja: ['落ち着いた', '親切な', 'とろけるような', 'わくわくする'],
    tags_en: ['calm', 'kind', 'mellow', 'heart-throbbing'],
    tags_zh: ['冷静的', '亲切的', '美妙的', '令人心动的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:44:02+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nyoungil',
    display_name_ko: '영일',
    display_name_ja: 'ヨンイル',
    display_name_en: 'Youngil',
    gender: 'M',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '빼앗긴 들에도 봄은 오는가?',
    },
    tags_ko: ['신뢰가는', '차분한', '개성있는', '느릿한'],
    tags_ja: ['信頼感を与える', '落ち着いた', '個性的な', 'ゆっくりの'],
    tags_en: ['trustworthy', 'calm', 'unique', 'slow'],
    tags_zh: ['可靠的', '冷静的', '有个性的', '缓慢的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:54:22+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nseungpyo',
    display_name_ko: '승표',
    display_name_ja: 'スンピョ',
    display_name_en: 'Seungpyo',
    gender: 'M',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '옛날 옛날에 아주 사이좋은 오누이가 살고 있었습니다.',
    },
    tags_ko: ['신뢰가는', '쓸쓸한', '차분한', '구수한', '느릿한'],
    tags_ja: [
      '信頼感を与える',
      '寂しげな',
      '落ち着いた',
      '人情味のある',
      'ゆっくりの',
    ],
    tags_en: ['trustworthy', 'lonely', 'calm', 'amusing', 'slow'],
    tags_zh: ['可靠的', '孤单的', '冷静的', '香浓的', '缓慢的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:35+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nwontak',
    display_name_ko: '원탁',
    display_name_ja: 'ウォンタク',
    display_name_en: 'Wontak',
    gender: 'M',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '늑대무리는 사냥에 나선다.',
    },
    tags_ko: ['신뢰가는', '쓸쓸한', '차분한', '개성있는', '느릿한'],
    tags_ja: [
      '信頼感を与える',
      '寂しげな',
      '落ち着いた',
      '個性的な',
      'ゆっくりの',
    ],
    tags_en: ['trustworthy', 'lonely', 'calm', 'unique', 'slow'],
    tags_zh: ['可靠的', '孤单的', '冷静的', '有个性的', '缓慢的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:35+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'neunyoung',
    display_name_ko: '은영',
    display_name_ja: 'ウニョン',
    display_name_en: 'Eunyoung',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '다음 보기 중에 가장 적절한 것을 골라주세요.',
    },
    tags_ko: ['신뢰가는', '친절한', '감미로운'],
    tags_ja: ['信頼感を与える', '親切な', 'とろけるような'],
    tags_en: ['trustworthy', 'kind', 'mellow'],
    tags_zh: ['可靠的', '亲切的', '美妙的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:35+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nsunkyung',
    display_name_ko: '선경',
    display_name_ja: 'ソンギョン',
    display_name_en: 'Sunkyung',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '다음 곡은 샐리님의 신청곡입니다.',
    },
    tags_ko: ['차분한', '매력적인', '감미로운', '사랑스러운'],
    tags_ja: ['落ち着いた', '魅力的な', 'とろけるような', 'ラブリーな'],
    tags_en: ['calm', 'charming', 'mellow', 'lovely'],
    tags_zh: ['冷静的', '有魅力的', '美妙的', '惹人喜爱的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:35+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nyujin',
    display_name_ko: '유진',
    display_name_ja: 'ユージン',
    display_name_en: 'Yujin',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '강을보며 걷다가 자기도 모르게 빠져드는 길이다.',
    },
    tags_ko: ['신뢰가는', '차분한', '감미로운', '친근한'],
    tags_ja: [
      '信頼感を与える',
      '落ち着いた',
      'とろけるような',
      'フレンドリーな',
    ],
    tags_en: ['trustworthy', 'calm', 'mellow', 'friendly'],
    tags_zh: ['可靠的', '冷静的', '美妙的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:35+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'ntomoko',
    display_name_ko: '토모코',
    display_name_ja: 'ともこ',
    display_name_en: 'Tomoko',
    gender: 'F',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はトモコです。',
    },
    tags_ko: ['수줍은', '친절한', '사랑스러운', '설레는', '조용한'],
    tags_ja: ['シャイな', '親切な', 'ラブリーな', 'わくわくする', '静かな'],
    tags_en: ['shy', 'kind', 'lovely', 'heart-throbbing', 'silent'],
    tags_zh: ['腼腆的', '亲切的', '惹人喜爱的', '令人心动的', '安静的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:44:12+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nsayuri',
    display_name_ko: '사유리',
    display_name_ja: 'さゆり',
    display_name_en: 'Sayuri',
    gender: 'F',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はさゆりです。',
    },
    tags_ko: ['활기찬', '싹싹한', '친절한', '털털한'],
    tags_ja: ['活気のある', '気さくな', '親切な', 'サバサバしている'],
    tags_en: ['energetic', 'affable', 'kind', 'easy-going'],
    tags_zh: ['有活力的', '善解人意的', '亲切的', '爽朗的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:52:09+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nnaomi',
    display_name_ko: '나오미',
    display_name_ja: 'なおみ',
    display_name_en: 'Naomi',
    gender: 'F',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はなおみです。',
    },
    tags_ko: ['차분한', '싹싹한', '친절한', '친근한'],
    tags_ja: ['落ち着いた', '気さくな', '親切な', 'フレンドリーな'],
    tags_en: ['calm', 'affable', 'kind', 'friendly'],
    tags_zh: ['冷静的', '善解人意的', '亲切的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:46:56+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'dara_ang',
    display_name_ko: '아라(화남)',
    display_name_ja: 'アラ(angry)',
    display_name_en: 'Ara (angry)',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '지금 뭐라고 하셨어요? 이 생쥐는 진짜 도둑이라고요!',
    },
    tags_ko: ['활기찬', '열정적인', '새침한', '친근한'],
    tags_ja: ['活気のある', '情熱的な', '取り澄ました', 'フレンドリーな'],
    tags_en: ['energetic', 'passionate', 'coy', 'friendly'],
    tags_zh: ['有活力的', '热情的', '傲娇的', '和蔼的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:35+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'chiahua',
    display_name_ko: '차화',
    display_name_ja: 'チャファ',
    display_name_en: 'Chiahua',
    gender: 'F',
    lang: 'zh-TW',
    age_group: 'youth',
    default_text: {
      '0': '你好, 见到你很高兴。',
    },
    tags_ko: ['차분한', '친절한', '설레는'],
    tags_ja: ['落ち着いた', '親切な', 'わくわくする'],
    tags_en: ['calm', 'kind', 'heart-throbbing'],
    tags_zh: ['冷静的', '亲切的', '令人心动的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'kuanlin',
    display_name_ko: '관린',
    display_name_ja: 'グァンリン',
    display_name_en: 'Kuanlin',
    gender: 'M',
    lang: 'zh-TW',
    age_group: 'youth',
    default_text: {
      '0': '你好, 见到你很高兴。',
    },
    tags_ko: ['신뢰가는', '차분한', '저음의'],
    tags_ja: ['信頼感を与える', '落ち着いた', '低音の'],
    tags_en: ['trustworthy', 'calm', 'low-pitched'],
    tags_zh: ['可靠的', '冷静的', '低音的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'dhajime',
    display_name_ko: '하지메',
    display_name_ja: 'はじめ',
    display_name_en: 'Hajime',
    gender: 'M',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私ははじめです。',
    },
    tags_ko: ['차분한', '친절한', '친근한'],
    tags_ja: ['落ち着いた', '親切な', 'フレンドリーな'],
    tags_en: ['calm', 'kind', 'friendly'],
    tags_zh: ['冷静的', '亲切的', '和蔼的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'ddaiki',
    display_name_ko: '다이키',
    display_name_ja: 'だいき',
    display_name_en: 'Daiki',
    gender: 'M',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はだいきです。',
    },
    tags_ko: ['싹싹한', '열정적인', '친절한'],
    tags_ja: ['気さくな', '情熱的な', '親切な'],
    tags_en: ['affable', 'passionate', 'kind'],
    tags_zh: ['善解人意的', '热情的', '亲切的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'dayumu',
    display_name_ko: '아유무',
    display_name_ja: 'あゆむ',
    display_name_en: 'Ayumu',
    gender: 'M',
    lang: 'ja',
    age_group: 'child',
    default_text: {
      '0': 'こんにちは。私はあゆむです。',
    },
    tags_ko: ['활기찬', '사랑스러운', '장난기있는', '호기심많은'],
    tags_ja: ['活気のある', 'ラブリーな', '茶目っ気のある', '好奇心旺盛な'],
    tags_en: ['energetic', 'lovely', 'playful', 'curious'],
    tags_zh: ['有活力的', '惹人喜爱的', '调皮的', '好奇心旺盛的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'dmio',
    display_name_ko: '미오',
    display_name_ja: 'みお',
    display_name_en: 'Mio',
    gender: 'F',
    lang: 'ja',
    age_group: 'child',
    default_text: {
      '0': 'こんにちは。私はみおです。',
    },
    tags_ko: ['활기찬', '사랑스러운', '설레는', '친근한', '호기심많은'],
    tags_ja: [
      '活気のある',
      'ラブリーな',
      'わくわくする',
      'フレンドリーな',
      '好奇心旺盛な',
    ],
    tags_en: ['energetic', 'lovely', 'heart-throbbing', 'friendly', 'curious'],
    tags_zh: ['有活力的', '惹人喜爱的', '令人心动的', '和蔼的', '好奇心旺盛的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'ntiffany',
    display_name_ko: '기서',
    display_name_ja: 'ギ��',
    display_name_en: 'Kiseo',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '모든 사람들에게 편안함을 주는 목소리를 들려주고 싶습니다.',
    },
    tags_ko: ['차분한', '싹싹한', '친절한'],
    tags_ja: ['落ち着いた', '気さくな', '親切な'],
    tags_en: ['calm', 'affable', 'kind'],
    tags_zh: ['冷静的', '善解人意的', '亲切的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'noyj',
    display_name_ko: '봄달',
    display_name_ja: 'ボンダル',
    display_name_en: 'Bomdal',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '사람들의 마음을 서로 연결해 줄 수 있다면, 정말 행복할 것 같아요.',
    },
    tags_ko: ['차분한', '친절한', '감미로운', '사랑스러운'],
    tags_ja: ['落ち着いた', '親切な', 'とろけるような', 'ラブリーな'],
    tags_en: ['calm', 'kind', 'mellow', 'lovely'],
    tags_zh: ['冷静的', '亲切的', '美妙的', '惹人喜爱的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njangj',
    display_name_ko: '드림',
    display_name_ja: 'ユーメ',
    display_name_en: 'Dream',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '꿈과 희망을 주는 목소리가 되어주고 싶습니다.',
    },
    tags_ko: ['신뢰가는', '차분한', '친절한', '사랑스러운'],
    tags_ja: ['信頼感を与える', '落ち着いた', '親切な', 'ラブリーな'],
    tags_en: ['trustworthy', 'calm', 'kind', 'lovely'],
    tags_zh: ['可靠的', '冷静的', '亲切的', '惹人喜爱的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'napple',
    display_name_ko: '늘봄',
    display_name_ja: 'ヨンボム',
    display_name_en: 'Neulbom',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '시련을 겪고 계신 분들에게, 따듯한 희망을 전하고 싶습니다.',
    },
    tags_ko: ['신뢰가는', '차분한', '감미로운'],
    tags_ja: ['信頼感を与える', '落ち着いた', 'とろけるような'],
    tags_en: ['trustworthy', 'calm', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '美妙的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'danna',
    display_name_ko: '안나',
    display_name_ja: 'アンナ',
    display_name_en: 'Anna',
    gender: 'F',
    lang: 'en',
    age_group: 'youth',
    default_text: {
      '0': 'Hello, I am Anna.',
    },
    tags_ko: ['활기찬', '싹싹한', '친근한', '털털한'],
    tags_ja: ['活気のある', '気さくな', 'フレンドリーな', 'サバサバしている'],
    tags_en: ['energetic', 'affable', 'friendly', 'easy-going'],
    tags_zh: ['有活力的', '善解人意的', '和蔼的', '爽朗的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'djoey',
    display_name_ko: '조이',
    display_name_ja: 'ジョーイ',
    display_name_en: 'Joey',
    gender: 'F',
    lang: 'en',
    age_group: 'child',
    default_text: {
      '0': 'Hello, I am Joey.',
    },
    tags_ko: ['활기찬', '사랑스러운', '설레는', '친근한'],
    tags_ja: ['活気のある', 'ラブリーな', 'わくわくする', 'フレンドリーな'],
    tags_en: ['energetic', 'lovely', 'heart-throbbing', 'friendly'],
    tags_zh: ['有活力的', '惹人喜爱的', '令人心动的', '和蔼的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'nsunhee',
    display_name_ko: '선희',
    display_name_ja: 'ソニ',
    display_name_en: 'Sunhee',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '어느 깊은 가을밤, 잠에서 깨어난 제자가 울고 있었다.',
    },
    tags_ko: ['신뢰가는', '차분한', '매력적인', '저음의'],
    tags_ja: ['信頼感を与える', '落ち着いた', '魅�的な', '低音の'],
    tags_en: ['trustworthy', 'calm', 'charming', 'low-pitched'],
    tags_zh: ['可靠的', '冷静的', '有魅力的', '低音的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nminseo',
    display_name_ko: '민서',
    display_name_ja: 'ミンサー',
    display_name_en: 'Minseo',
    gender: 'F',
    lang: 'ko',
    age_group: 'teen',
    default_text: {
      '0': '3월부터 점심시간에 학교 소식을 전해드릴 방송반 민서입니다.',
    },
    tags_ko: ['차분한', '사랑스러운', '설레는', '친근한'],
    tags_ja: ['落ち着いた', 'ラブリーな', 'わくわくする', 'フレンドリーな'],
    tags_en: ['calm', 'lovely', 'heart-throbbing', 'friendly'],
    tags_zh: ['冷静的', '惹人喜爱的', '令人心动的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njiwon',
    display_name_ko: '지원',
    display_name_ja: 'ジウォン',
    display_name_en: 'Jiwon',
    gender: 'F',
    lang: 'ko',
    age_group: 'teen',
    default_text: {
      '0': '이번 중간고사 시험은 운이 좋았어요.',
    },
    tags_ko: ['차분한', '싹싹한', '친근한'],
    tags_ja: ['落ち着いた', '気さくな', 'フレンドリーな'],
    tags_en: ['calm', 'affable', 'friendly'],
    tags_zh: ['冷静的', '善解人意的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nbora',
    display_name_ko: '보라',
    display_name_ja: 'ボラ',
    display_name_en: 'Bora',
    gender: 'F',
    lang: 'ko',
    age_group: 'teen',
    default_text: {
      '0': '언제부터 학교에 나갈수 있을까요?',
    },
    tags_ko: ['차분한', '열정적인', '사랑스러운', '새침한', '무뚝뚝한'],
    tags_ja: [
      '落ち着いた',
      '情熱的な',
      'ラブリーな',
      '取り澄ました',
      '無愛想な',
    ],
    tags_en: ['calm', 'passionate', 'lovely', 'coy', 'blunt'],
    tags_zh: ['冷静的', '热情的', '惹人喜爱的', '傲娇的', '沉默寡言的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njonghyun',
    display_name_ko: '종현',
    display_name_ja: 'ジョンヒョン',
    display_name_en: 'Jonghyun',
    gender: 'M',
    lang: 'ko',
    age_group: 'teen',
    default_text: {
      '0': '2021년 학생회장에 당선된 종현이입니다.',
    },
    tags_ko: ['차분한', '열정적인', '친절한'],
    tags_ja: ['落ち着いた', '情熱的な', '親切な'],
    tags_en: ['calm', 'passionate', 'kind'],
    tags_zh: ['冷静的', '热情的', '亲切的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njoonyoung',
    display_name_ko: '준영',
    display_name_ja: 'ジュンヨン',
    display_name_en: 'Joonyoung',
    gender: 'M',
    lang: 'ko',
    age_group: 'teen',
    default_text: {
      '0': '미리 과목 구성과 학습법을',
    },
    tags_ko: ['쓸쓸한', '차분한', '친근한', '무뚝뚝한', '느릿한'],
    tags_ja: [
      '寂しげな',
      '落ち着いた',
      'フレンドリーな',
      '無愛想な',
      'ゆっくりの',
    ],
    tags_en: ['lonely', 'calm', 'friendly', 'blunt', 'slow'],
    tags_zh: ['孤单的', '冷静的', '和蔼的', '沉默寡言的', '缓慢的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njaewook',
    display_name_ko: '재욱',
    display_name_ja: 'ジェウク',
    display_name_en: 'Jaewook',
    gender: 'M',
    lang: 'ko',
    age_group: 'teen',
    default_text: {
      '0': '다음은 근의 공식을 유도하는 과정입니다.',
    },
    tags_ko: ['차분한', '싹싹한', '열정적인', '친근한'],
    tags_ja: ['落ち着いた', '気さくな', '情熱的な', 'フレンドリーな'],
    tags_en: ['calm', 'affable', 'passionate', 'friendly'],
    tags_zh: ['冷静的', '善解人意的', '热情的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'driko',
    display_name_ko: '리코',
    display_name_ja: 'りこ',
    display_name_en: 'Riko',
    gender: 'F',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はリコです。',
    },
    tags_ko: ['활기찬', '사랑스러운', '장난기있는', '개성있는'],
    tags_ja: ['活気のある', 'ラブリーな', '茶目っ気のある', '個性的な'],
    tags_en: ['energetic', 'lovely', 'playful', 'unique'],
    tags_zh: ['有活力的', '惹人喜爱的', '调皮的', '有个性的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'deriko',
    display_name_ko: '에리코',
    display_name_ja: 'えりこ',
    display_name_en: 'Eriko',
    gender: 'F',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はえりこです。',
    },
    tags_ko: ['신뢰가는', '차분한', '털털한'],
    tags_ja: ['信頼感を与える', '落ち着いた', 'サバサバしている'],
    tags_en: ['trustworthy', 'calm', 'easy-going'],
    tags_zh: ['可靠的', '冷静的', '爽朗的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'dnaomi_joyful',
    display_name_ko: '나오미(기쁨)',
    display_name_ja: 'なおみ(joy)',
    display_name_en: 'Naomi',
    gender: 'F',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はなおみです。',
    },
    tags_ko: ['활기찬', '친절한', '친근한'],
    tags_ja: ['活気のある', '親切な', 'フレンドリーな'],
    tags_en: ['energetic', 'kind', 'friendly'],
    tags_zh: ['有活力的', '亲切的', '和蔼的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'dnaomi_formal',
    display_name_ko: '나오미(뉴스)',
    display_name_ja: 'なおみ(formal)',
    display_name_en: 'Naomi',
    gender: 'F',
    lang: 'ja',
    age_group: 'youth',
    default_text: {
      '0': 'こんにちは。私はなおみです。',
    },
    tags_ko: ['신뢰가는', '차분한'],
    tags_ja: ['信頼感を与える', '落ち着いた'],
    tags_en: ['trustworthy', 'calm'],
    tags_zh: ['可靠的', '冷静的'],
    engine: 'NVOICE',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'nara_call',
    display_name_ko: '아라(상담원)',
    display_name_ja: 'アラ(エージェント)',
    display_name_en: 'Ara (customer service)',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '네 고객님, 어떻게 도와드리면 될까요?',
    },
    tags_ko: ['신뢰가는', '활기찬', '차분한', '싹싹한', '친절한'],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '落ち着いた',
      '気さくな',
      '親切な',
    ],
    tags_en: ['trustworthy', 'energetic', 'calm', 'affable', 'kind'],
    tags_zh: ['可靠的', '有活力的', '冷静的', '善解人意的', '亲切的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nminyoung',
    display_name_ko: '민영',
    display_name_ja: 'ミニョン',
    display_name_en: 'Minyoung',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '자기의 힘을 자랑하는 바람과 지혜로운 해님이 살고 있었어요.',
    },
    tags_ko: ['신뢰가는', '활기찬', '싹싹한', '친절한', '사랑스러운'],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '気さくな',
      '親切な',
      'ラブリーな',
    ],
    tags_en: ['trustworthy', 'energetic', 'affable', 'kind', 'lovely'],
    tags_zh: ['可靠的', '有活力的', '善解人意的', '亲切的', '惹人喜爱的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'ngaram',
    display_name_ko: '가람',
    display_name_ja: 'ガラム',
    display_name_en: 'Garam',
    gender: 'F',
    lang: 'ko',
    age_group: 'child',
    default_text: {
      '0': '저는 새로운 곳을 탐험하는 걸 좋아해요.',
    },
    tags_ko: ['활기찬', '열정적인', '사랑스러운', '장난기있는'],
    tags_ja: ['活気のある', '情熱的な', 'ラブリーな', '茶目っ気のある'],
    tags_en: ['energetic', 'passionate', 'lovely', 'playful'],
    tags_zh: ['有活力的', '热情的', '惹人喜爱的', '调皮的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nyejin',
    display_name_ko: '예진',
    display_name_ja: 'イェジン',
    display_name_en: 'Yejin',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '어쨌든 우린 제대로 찾아 왔어. 일단 도착하면 다 알게 되겠지 뭐.',
    },
    tags_ko: ['활기찬', '열정적인', '매력적인', '새침한', '친근한', '풍부한'],
    tags_ja: [
      '活気のある',
      '情熱的な',
      '魅力的な',
      '取り澄ました',
      'フレンドリーな',
      '響きの豊かな',
    ],
    tags_en: ['energetic', 'passionate', 'charming', 'coy', 'friendly', 'rich'],
    tags_zh: ['有活力的', '热情的', '有魅力的', '傲娇的', '和蔼的', '丰富的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njooahn',
    display_name_ko: '주안',
    display_name_ja: 'ジュアン',
    display_name_en: 'Jooahn',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '당신에겐, 꿈을 이루기에 충분한 시간이 있어요!',
    },
    tags_ko: ['신뢰가는', '활기찬', '친절한', '감미로운'],
    tags_ja: ['信頼感を与える', '活気のある', '親切な', 'とろけるような'],
    tags_en: ['trustworthy', 'energetic', 'kind', 'mellow'],
    tags_zh: ['可靠的', '有活力的', '亲切的', '美妙的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nseonghoon',
    display_name_ko: '성훈',
    display_name_ja: 'ソンフン',
    display_name_en: 'Sunghoon',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '내 모든걸 쏟아 부어서, 아무것도 남은게 없어.',
    },
    tags_ko: [
      '활기찬',
      '열정적인',
      '매력적인',
      '개성있는',
      '카리스마있는',
      '풍부한',
    ],
    tags_ja: [
      '活気のある',
      '情熱的な',
      '魅力的な',
      '個性的な',
      'カリスマ性のある',
      '響きの豊かな',
    ],
    tags_en: [
      'energetic',
      'passionate',
      'charming',
      'unique',
      'charismatic',
      'rich',
    ],
    tags_zh: ['有活力的', '热情的', '有魅力的', '有个性的', '高冷的', '丰富的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njihwan',
    display_name_ko: '지환',
    display_name_ja: 'ジファン',
    display_name_en: 'Jihwan',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '나는 너가 더 행복해졌으면 좋겠어.',
    },
    tags_ko: ['신뢰가는', '차분한', '저음의', '친근한'],
    tags_ja: ['信頼感を与える', '落ち着いた', '低音の', 'フレンドリーな'],
    tags_en: ['trustworthy', 'calm', 'low-pitched', 'friendly'],
    tags_zh: ['可靠的', '冷静的', '低音的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nsiyoon',
    display_name_ko: '시윤',
    display_name_ja: 'シユン',
    display_name_en: 'Siyoon',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '우리의 걱정들은 자고 일어나면 별일 아니더라구요.',
    },
    tags_ko: ['신뢰가는', '쓸쓸한', '차분한', '친절한', '친근한'],
    tags_ja: [
      '信頼感を与える',
      '寂しげな',
      '落ち着いた',
      '親切な',
      'フレンドリーな',
    ],
    tags_en: ['trustworthy', 'lonely', 'calm', 'kind', 'friendly'],
    tags_zh: ['可靠的', '孤单的', '冷静的', '亲切的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:36+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nes_c_mikyung',
    display_name_ko: '미경',
    display_name_ja: 'ミギョン',
    display_name_en: 'Mikyung',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '눈물을 글썽이고 있는데, 누군가가 이렇게 말하는 거예요.',
    },
    tags_ko: ['신뢰가는', '활기찬', '싹싹한', '매력적인', '사랑스러운'],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '気さくな',
      '魅力的な',
      'ラブリーな',
    ],
    tags_en: ['trustworthy', 'energetic', 'affable', 'charming', 'lovely'],
    tags_zh: ['可靠的', '有活力的', '善解人意的', '有魅力的', '惹人喜爱的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nes_c_kihyo',
    display_name_ko: '기효',
    display_name_ja: 'ギヒョ',
    display_name_en: 'Kihyo',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '지금 보시면 이부분, 가지색이라고 제가 표현할게요.',
    },
    tags_ko: ['활기찬', '열정적인', '친절한', '장난기있는', '구매유발하는'],
    tags_ja: [
      '活気のある',
      '情熱的な',
      '親切な',
      '茶目っ気のある',
      '購買意欲をそそる',
    ],
    tags_en: ['energetic', 'passionate', 'kind', 'playful', 'pitchable'],
    tags_zh: ['有活力的', '热情的', '亲切的', '调皮的', '激发购买欲的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nes_c_hyeri',
    display_name_ko: '혜리',
    display_name_ja: 'ヘリ',
    display_name_en: 'Hyeri',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '오늘 들어오시는 분들은요, 특별히 추가 선물 구성으로 준비를 해드리는데요.',
    },
    tags_ko: ['활기찬', '싹싹한', '열정적인', '구매유발하는', '속도감있는'],
    tags_ja: [
      '活気のある',
      '気さくな',
      '情熱的な',
      '購買意欲をそそる',
      'スピード感のある',
    ],
    tags_en: ['energetic', 'affable', 'passionate', 'pitchable', 'speedy'],
    tags_zh: ['有活力的', '善解人意的', '热情的', '激发购买欲的', '有速度感的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nes_c_sohyun',
    display_name_ko: '소현',
    display_name_ja: 'ソヒョン',
    display_name_en: 'Sohyun',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '딱 하나만 발랐을 뿐인데, 방긋해지는 느낌 있지 않아요?',
    },
    tags_ko: ['활기찬', '싹싹한', '털털한', '구매유발하는'],
    tags_ja: ['活気のある', '気さくな', 'サバサバしている', '購買意欲をそそる'],
    tags_en: ['energetic', 'affable', 'easy-going', 'pitchable'],
    tags_zh: ['有活力的', '善解人意的', '爽朗的', '激发购买欲的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nminjeong',
    display_name_ko: '민정',
    display_name_ja: 'ミンジョン',
    display_name_en: 'Minjeong',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '아삭아삭 맛있는 무 냉채. 어떻게 만들 수 있을까요?',
    },
    tags_ko: ['활기찬', '열정적인', '매력적인', '친절한'],
    tags_ja: ['活気のある', '情熱的な', '魅力的な', '親切な'],
    tags_en: ['energetic', 'passionate', 'charming', 'kind'],
    tags_zh: ['有活力的', '热情的', '有魅力的', '亲切的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nkyungtae',
    display_name_ko: '경태',
    display_name_ja: 'ギョンテ',
    display_name_en: 'Kyungtae',
    gender: 'M',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '옛날 옛날 아주 먼 옛날. 어느 마을에서 있던 일이었어요.',
    },
    tags_ko: ['신뢰가는', '활기찬', '장난기있는', '구수한', '개성있는'],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '茶目っ気のある',
      '人情味のある',
      '個性的な',
    ],
    tags_en: ['trustworthy', 'energetic', 'playful', 'amusing', 'unique'],
    tags_zh: ['可靠的', '有活力的', '调皮的', '香浓的', '有个性的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nraewon',
    display_name_ko: '래원',
    display_name_ja: 'レウォン',
    display_name_en: 'Raewon',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '그녀석은 평범한 꼬마가 아니야.',
    },
    tags_ko: ['신뢰가는', '활기찬', '열정적인', '카리스마있는'],
    tags_ja: ['信頼感を与える', '活気のある', '情熱的な', 'カリスマ性のある'],
    tags_en: ['trustworthy', 'energetic', 'passionate', 'charismatic'],
    tags_zh: ['可靠的', '有活力的', '热情的', '高冷的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nkyuwon',
    display_name_ko: '규원',
    display_name_ja: 'ギュウォン',
    display_name_en: 'Kyuwon',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '때마침 그 곳을 지나던 안나의 도움을 받게됩니다.',
    },
    tags_ko: ['차분한', '친절한', '친근한'],
    tags_ja: ['落ち着いた', '親切な', 'フレンドリーな'],
    tags_en: ['calm', 'kind', 'friendly'],
    tags_zh: ['冷静的', '亲切的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nihyun',
    display_name_ko: '이현',
    display_name_ja: 'イヒョン',
    display_name_en: 'ihyun',
    gender: 'F',
    lang: 'ko',
    age_group: 'teen',
    default_text: {
      '0': '그래서 일주일 동안 정말 재밌게 보내고 왔답니다.',
    },
    tags_ko: ['활기찬', '사랑스러운', '새침한', '친근한'],
    tags_ja: ['活気のある', 'ラブリーな', '取り澄ました', 'フレンドリーな'],
    tags_en: ['energetic', 'lovely', 'coy', 'friendly'],
    tags_zh: ['有活力的', '惹人喜爱的', '傲娇的', '和蔼的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nyoungmi',
    display_name_ko: '영미',
    display_name_ja: 'ヨンミ',
    display_name_en: 'Youngmi',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '변하지 않는건 사람들의 마음이죠.',
    },
    tags_ko: [
      '활기찬',
      '열정적인',
      '매력적인',
      '사랑스러운',
      '장난기있는',
      '새침한',
    ],
    tags_ja: [
      '活気のある',
      '情熱的な',
      '魅力的な',
      'ラブリーな',
      '茶目っ気のある',
      '取り澄ました',
    ],
    tags_en: [
      'energetic',
      'passionate',
      'charming',
      'lovely',
      'playful',
      'coy',
    ],
    tags_zh: [
      '有活力的',
      '热情的',
      '有魅力的',
      '惹人喜爱的',
      '调皮的',
      '傲娇的',
    ],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'neunseo',
    display_name_ko: '은서',
    display_name_ja: 'ウンソ',
    display_name_en: 'Eunseo',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '나에게 대항하는 자. 용서치 않겠다.',
    },
    tags_ko: ['매력적인', '새침한', '개성있는', '카리스마있는'],
    tags_ja: ['魅力的な', '取り澄ました', '個性的な', 'カリスマ性のある'],
    tags_en: ['charming', 'coy', 'unique', 'charismatic'],
    tags_zh: ['有魅力的', '傲娇的', '有个性的', '高冷的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nkyunglee',
    display_name_ko: '경리',
    display_name_ja: 'ギョンリー',
    display_name_en: 'Kyunglee',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '서양음악의 뿌리자체가 흔들린다고 할 정도로 발달했습니다.',
    },
    tags_ko: ['신뢰가는', '차분한', '매력적인', '새침한', '무뚝뚝한'],
    tags_ja: [
      '信頼感を与える',
      '落ち着いた',
      '魅力的な',
      '取り澄ました',
      '無愛想な',
    ],
    tags_en: ['trustworthy', 'calm', 'charming', 'coy', 'blunt'],
    tags_zh: ['可靠的', '冷静的', '有魅力的', '傲娇的', '沉默寡言的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nheera',
    display_name_ko: '희라',
    display_name_ja: 'ヒラ',
    display_name_en: 'Heera',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '우리가 쫓던 실종사건의 본질에 집중하죠.',
    },
    tags_ko: ['신뢰가는', '매력적인', '감미로운', '카리스마있는'],
    tags_ja: [
      '信頼感を与える',
      '魅力的な',
      'とろけるような',
      'カリスマ性のある',
    ],
    tags_en: ['trustworthy', 'charming', 'mellow', 'charismatic'],
    tags_zh: ['可靠的', '有魅力的', '美妙的', '高冷的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'neunwoo',
    display_name_ko: '은우',
    display_name_ja: 'ウンウ',
    display_name_en: 'Eunwoo',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '1년에 단 하루. 당신의 특별한 크리스마스.',
    },
    tags_ko: ['활기찬', '싹싹한', '열정적인', '친근한', '구매유발하는'],
    tags_ja: [
      '活気のある',
      '気さくな',
      '情熱的な',
      'フレンドリーな',
      '購買意欲をそそる',
    ],
    tags_en: ['energetic', 'affable', 'passionate', 'friendly', 'pitchable'],
    tags_zh: ['有活力的', '善解人意的', '热情的', '和蔼的', '激发购买欲的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nwoosik',
    display_name_ko: '우식',
    display_name_ja: 'ウシク',
    display_name_en: 'Woosik',
    gender: 'M',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '클로바더빙에서 뜨끈한 AI 보이스들을 만나 보세요.',
    },
    tags_ko: [
      '신뢰가는',
      '활기찬',
      '열정적인',
      '친근한',
      '구매유발하는',
      '풍부한',
    ],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '情熱的な',
      'フレンドリーな',
      '購買意欲をそそる',
      '響きの豊かな',
    ],
    tags_en: [
      'trustworthy',
      'energetic',
      'passionate',
      'friendly',
      'pitchable',
      'rich',
    ],
    tags_zh: [
      '可靠的',
      '有活力的',
      '热情的',
      '和蔼的',
      '激发购买欲的',
      '丰富的',
    ],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nkitae',
    display_name_ko: '기태',
    display_name_ja: 'ギテ',
    display_name_en: 'Kitae',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '소상공인에게 힘이 된 것은 물론, 지역경제 선순환 효과까지.',
    },
    tags_ko: ['신뢰가는', '활기찬', '싹싹한', '매력적인', '장난기있는'],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '気さくな',
      '魅力的な',
      '茶目っ気のある',
    ],
    tags_en: ['trustworthy', 'energetic', 'affable', 'charming', 'playful'],
    tags_zh: ['可靠的', '有活力的', '善解人意的', '有魅力的', '调皮的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nyeji',
    display_name_ko: '예지',
    display_name_ja: 'イェジ',
    display_name_en: 'Yeji',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '난 이렇게 존재한다구. 너희가 보는 그대로.',
    },
    tags_ko: ['활기찬', '열정적인', '매력적인', '새침한', '털털한'],
    tags_ja: [
      '活気のある',
      '情熱的な',
      '魅力的な',
      '取り澄ました',
      'サバサバしている',
    ],
    tags_en: ['energetic', 'passionate', 'charming', 'coy', 'easy-going'],
    tags_zh: ['有活力的', '热情的', '有魅力的', '傲娇的', '爽朗的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nyuna',
    display_name_ko: '유나',
    display_name_ja: 'ユナ',
    display_name_en: 'Yuna',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '일칠팔사에 도착. 인턴으로 첫 출근합니다.',
    },
    tags_ko: ['활기찬', '싹싹한', '친절한', '새침한'],
    tags_ja: ['活気のある', '気さくな', '親切な', '取り澄ました'],
    tags_en: ['energetic', 'affable', 'kind', 'coy'],
    tags_zh: ['有活力的', '善解人意的', '亲切的', '傲娇的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nnarae',
    display_name_ko: '나래',
    display_name_ja: 'ナレ',
    display_name_en: 'Narae',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '오랜만에 돌아온 우리집. 우리집만큼 편한 곳이 없다.',
    },
    tags_ko: ['차분한', '싹싹한', '열정적인', '친근한', '털털한'],
    tags_ja: [
      '落ち着いた',
      '気さくな',
      '情熱的な',
      'フレンドリーな',
      'サバサバしている',
    ],
    tags_en: ['calm', 'affable', 'passionate', 'friendly', 'easy-going'],
    tags_zh: ['冷静的', '善解人意的', '热情的', '和蔼的', '爽朗的'],
    engine: 'NES',
    serviced_at: '2022-10-07T11:56:37+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vara',
    display_name_ko: '아라',
    display_name_ja: 'アラ',
    display_name_en: 'Ara',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '오늘도 소소한 일상 속에서, 행복을 찾는 즐거운 하루 되시길 바래요.',
      '1': '오늘따라 밤이 왜 이렇게 깜깜한지, 조금 무서운 기분이 드네요.',
      '2': '당신은 어떻게 이렇게 따뜻한 마음씨를 가질 수가 있어요?',
      '3': '기분 좋은 얘기나 하라고 했더니 기분 나쁜 얘기를 해서 분위기를 망쳐?',
    },
    tags_ko: ['활기찬', '차분한', '매력적인', '친절한', '사랑스러운'],
    tags_ja: ['活気のある', '落ち着いた', '魅力的な', '親切な', 'ラブリーな'],
    tags_en: ['energetic', 'calm', 'charming', 'kind', 'lovely'],
    tags_zh: ['有活力的', '冷静的', '有魅力的', '亲切的', '惹人喜爱的'],
    engine: 'NEUVIS',
    serviced_at: '2022-12-12T16:42:04+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: true,
      'emotion-strength': true,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vhyeri',
    display_name_ko: '혜리',
    display_name_ja: 'ヘリ',
    display_name_en: 'Hyeri',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '오늘 들어오시는 분들은요, 특별히 추가 선물 구성으로 준비를 해드리는데요.',
    },
    tags_ko: ['활기찬', '싹싹한', '열정적인', '구매유발하는', '속도감있는'],
    tags_ja: [
      '活気のある',
      '気さくな',
      '情熱的な',
      '購買意欲をそそる',
      'スピード感のある',
    ],
    tags_en: ['energetic', 'affable', 'passionate', 'pitchable', 'speedy'],
    tags_zh: ['有活力的', '善解人意的', '热情的', '激发购买欲的', '有速度感的'],
    engine: 'NEUVIS',
    serviced_at: '2022-12-12T16:42:04+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vmikyung',
    display_name_ko: '미경',
    display_name_ja: 'ミギョン',
    display_name_en: 'Mikyung',
    gender: 'F',
    lang: 'ko',
    age_group: 'middle-aged and above',
    default_text: {
      '0': '눈물을 글썽이고 있는데, 누군가가 이렇게 말하는 거예요.',
      '1': '나는 엄마가 그렇게 엉엉 우는 건 처음 봤어요.',
      '2': '요정 아주머니가 커다란 풍선을 타고 하늘 높이 올라갔어요.',
      '3': '악당이 되고 싶다면 화통 삶아 먹은 듯한 큰 목소리는 필수지.',
    },
    tags_ko: ['신뢰가는', '활기찬', '싹싹한', '매력적인', '사랑스러운'],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '気さくな',
      '魅力的な',
      'ラブリーな',
    ],
    tags_en: ['trustworthy', 'energetic', 'affable', 'charming', 'lovely'],
    tags_zh: ['可靠的', '有活力的', '善解人意的', '有魅力的', '惹人喜爱的'],
    engine: 'NEUVIS',
    serviced_at: '2022-12-12T16:42:04+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: true,
      'emotion-strength': true,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vdain',
    display_name_ko: '다인',
    display_name_ja: 'ダイン ',
    display_name_en: 'Dain',
    gender: 'F',
    lang: 'ko',
    age_group: 'child',
    default_text: {
      '0': '저 하늘에 있는 구름은 무슨 맛일까요?',
      '1': '바게트를 크게 한입 베어먹다가 입천장이 까졌어요.',
      '2': '빠진 앞니를 이빨 요정에게 선물하면 선물을 준대!',
      '3': '어떻게 깨끗한 얼음이 아니라 하늘에서 내린 더러운 눈으로 빙수를 만들죠?',
    },
    tags_ko: ['활기찬', '사랑스러운', '설레는', '호기심많은'],
    tags_ja: ['活気のある', 'ラブリーな', 'わくわくする', '好奇心旺盛な'],
    tags_en: ['energetic', 'lovely', 'heart-throbbing', 'curious'],
    tags_zh: ['有活力的', '惹人喜爱的', '令人心动的', '好奇心旺盛的'],
    engine: 'NEUVIS',
    serviced_at: '2022-12-12T16:42:04+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: true,
      'emotion-strength': true,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vyuna',
    display_name_ko: '유나',
    display_name_ja: 'ユナ',
    display_name_en: 'Yuna',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '일칠팔사에 도착. 인턴으로 첫 출근합니다.',
      '1': '저도 그걸 모르는 게 아니지만 겁이 나서 못하겠단 말이에요.',
      '2': '나에게 용기를 주신 선생님께 감사하단 말씀 전할 생각이야.',
      '3': '꼼꼼하게 안 하고 뭐든지 적당히 넘어가려는 태도 때문에 불량이 나오잖아요!',
    },
    tags_ko: ['활기찬', '싹싹한', '친절한', '새침한'],
    tags_ja: ['活気のある', '気さくな', '親切な', '取り澄ました'],
    tags_en: ['energetic', 'affable', 'kind', 'coy'],
    tags_zh: ['有活力的', '善解人意的', '亲切的', '傲娇的'],
    engine: 'NEUVIS',
    serviced_at: '2022-12-12T16:42:04+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: true,
      'emotion-strength': true,
      'end-pitch': false,
    },
  },
  {
    speaker: 'dara-danna',
    display_name_ko: '아라&안나',
    display_name_ja: 'アラ&アンナ',
    display_name_en: 'Ara&Ann',
    gender: 'F',
    lang: 'ko+en',
    age_group: 'youth',
    default_text: {
      '0': '매일 30분으로 여러분도 Fluent English speaker가 될 수 있어요.',
    },
    tags_ko: ['활기찬', '차분한', '매력적인', '친절한', '사랑스러운'],
    tags_ja: ['活気のある', '落ち着いた', '魅力的な', '親切な', 'ラブリーな'],
    tags_en: ['energetic', 'calm', 'charming', 'kind', 'lovely'],
    tags_zh: ['有活力的', '冷静的', '有魅力的', '亲切的', '惹人喜爱的'],
    engine: '',
    serviced_at: '2023-02-23T20:50:25+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'dsinu-matt',
    display_name_ko: '신우&매트',
    display_name_ja: 'シンウ&マット',
    display_name_en: 'Shinwoo&Matt',
    gender: 'M',
    lang: 'ko+en',
    age_group: 'youth',
    default_text: {
      '0': 'ABC Learning English 사이트는 improvement of spoken English를 목표로 합니다. ',
    },
    tags_ko: ['신뢰가는', '차분한', '싹싹한', '매력적인', '감미로운'],
    tags_ja: [
      '信頼感を与える',
      '落ち着いた',
      '気さくな',
      '魅力的な',
      'とろけるような',
    ],
    tags_en: ['trustworthy', 'calm', 'affable', 'charming', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '善解人意的', '有魅力的', '美妙的'],
    engine: '',
    serviced_at: '2023-02-23T20:50:25+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': true,
    },
  },
  {
    speaker: 'nmammon',
    display_name_ko: '악마 마몬',
    display_name_ja: '悪魔マモン',
    display_name_en: 'Mammon the devil',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '은하계를 부수며 막힘없이 나아가면 미래의 우리는 정복자가 될지어다.',
    },
    tags_ko: ['매력적인', '개성있는', '카리스마있는', '풍부한'],
    tags_ja: ['魅力的な', '個性的な', 'カリスマ性のある', '響きの豊かな'],
    tags_en: ['charming', 'unique', 'charismatic', 'rich'],
    tags_zh: ['有魅力的', '有个性的', '高冷的', '丰富的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:34:22+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nmeow',
    display_name_ko: '야옹이',
    display_name_ja: 'ネコちゃん',
    display_name_en: 'Meow',
    gender: 'F',
    lang: 'ko',
    age_group: 'child',
    default_text: {
      '0': '우와, 착한 마음을 가지고 살겠다고 다짐하니까, 등 뒤에 작은 날개가 돋았어.',
    },
    tags_ko: [
      '활기찬',
      '사랑스러운',
      '새침한',
      '고음의',
      '금쪽같은',
      '호기심많은',
    ],
    tags_ja: [
      '活気のある',
      'ラブリーな',
      '取り澄ました',
      '高音の',
      '大切な',
      '好奇心旺盛な',
    ],
    tags_en: [
      'energetic',
      'lovely',
      'coy',
      'high-pitched',
      'precious',
      'curious',
    ],
    tags_zh: [
      '有活力的',
      '惹人喜爱的',
      '傲娇的',
      '高音的',
      '洪亮的',
      '好奇心旺盛的',
    ],
    engine: 'NES',
    serviced_at: '2023-04-20T18:34:26+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nwoof',
    display_name_ko: '멍멍이',
    display_name_ja: 'ワンちゃん',
    display_name_en: 'Woof',
    gender: 'M',
    lang: 'ko',
    age_group: 'child',
    default_text: {
      '0': '계속 엄마 생각이 나고, 엄마 냄새를 맡고 싶은게 바로 사랑이라는 거예요?',
    },
    tags_ko: [
      '활기찬',
      '사랑스러운',
      '고음의',
      '금쪽같은',
      '풍부한',
      '호기심많은',
    ],
    tags_ja: [
      '活気のある',
      'ラブリーな',
      '高音の',
      '大切な',
      '響きの豊かな',
      '好奇心旺盛な',
    ],
    tags_en: [
      'energetic',
      'lovely',
      'high-pitched',
      'precious',
      'rich',
      'curious',
    ],
    tags_zh: [
      '有活力的',
      '惹人喜爱的',
      '高音的',
      '洪亮的',
      '丰富的',
      '好奇心旺盛的',
    ],
    engine: 'NES',
    serviced_at: '2023-04-20T18:34:32+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nreview',
    display_name_ko: '박리뷰',
    display_name_ja: 'キム・レビュー',
    display_name_en: 'Review Park',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '돌아온 크리스마스 시즌, 이때는 누구나 사랑할 준비가 되어있겠죠?',
    },
    tags_ko: ['신뢰가는', '차분한', '감미로운', '설레는'],
    tags_ja: ['信頼感を与える', '落ち着いた', 'とろけるような', 'わくわくする'],
    tags_en: ['trustworthy', 'calm', 'mellow', 'heart-throbbing'],
    tags_zh: ['可靠的', '冷静的', '美妙的', '令人心动的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:34:47+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nyounghwa',
    display_name_ko: '정영화',
    display_name_ja: 'チョン・ヨンファ',
    display_name_en: 'Younghwa Jung',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '나무를 숨기려면 숲에 숨기란 말이 있듯, 범인은 도시 속에서 평범한 사람인 척 위장했죠.',
    },
    tags_ko: ['신뢰가는', '차분한', '싹싹한', '감미로운'],
    tags_ja: ['信頼感を与える', '落ち着いた', '気さくな', 'とろけるような'],
    tags_en: ['trustworthy', 'calm', 'affable', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '善解人意的', '美妙的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:35:05+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nmovie',
    display_name_ko: '최무비',
    display_name_ja: 'チェ・ムビ',
    display_name_en: 'Movie Choi',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '수군대는 군중들 사이로 씨익 웃는 한 남자, 명선은 그를 뒤쫓아 갑니다.',
    },
    tags_ko: ['신뢰가는', '차분한', '싹싹한', '감미로운'],
    tags_ja: ['信頼感を与える', '落ち着いた', '気さくな', 'とろけるような'],
    tags_en: ['trustworthy', 'calm', 'affable', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '善解人意的', '美妙的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:35:42+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nsangdo',
    display_name_ko: '상도',
    display_name_ja: 'サンド',
    display_name_en: 'Sangdo',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '히히, 겨울 간식으로는 떡 꾸버가지고 조청에 찍어먹는 게 제일이다.',
    },
    tags_ko: ['구수한', '친근한', '개성있는', '풍부한'],
    tags_ja: ['人情味のある', 'フレンドリーな', '個性的な', '響きの豊かな'],
    tags_en: ['amusing', 'friendly', 'unique', 'rich'],
    tags_zh: ['香浓的', '和蔼的', '有个性的', '丰富的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:35:48+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nshasha',
    display_name_ko: '샤샤',
    display_name_ja: 'シャシャ',
    display_name_en: 'Shasha',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '어디 다녀오는 길이세요?',
    },
    tags_ko: ['차분한', '친절한', '사랑스러운', '설레는'],
    tags_ja: ['落ち着いた', '親切な', 'ラブリーな', 'わくわくする'],
    tags_en: ['calm', 'kind', 'lovely', 'heart-throbbing'],
    tags_zh: ['冷静的', '亲切的', '惹人喜爱的', '令人心动的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:36:26+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nsabina',
    display_name_ko: '마녀 사비나',
    display_name_ja: '魔女サビナ',
    display_name_en: 'Sabina the witch',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '대지에 피는 한 송이 죽음의 꽃, 날 부르는 또 다른 이름이죠.',
    },
    tags_ko: ['매력적인', '개성있는', '카리스마있는', '풍부한'],
    tags_ja: ['魅力的な', '個性的な', 'カリスマ性のある', '響きの豊かな'],
    tags_en: ['charming', 'unique', 'charismatic', 'rich'],
    tags_zh: ['有魅力的', '有个性的', '高冷的', '丰富的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:44:44+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'ndonghyun',
    display_name_ko: '동현',
    display_name_ja: 'ドンヒョン',
    display_name_en: 'Donghyun',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '집에서 포장마차 감성으로 오뎅 한 접시 어떠세요?',
    },
    tags_ko: ['신뢰가는', '활기찬', '싹싹한', '열정적인', '구매유발하는'],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '気さくな',
      '情熱的な',
      '購買意欲をそそる',
    ],
    tags_en: ['trustworthy', 'energetic', 'affable', 'passionate', 'pitchable'],
    tags_zh: ['可靠的', '有活力的', '善解人意的', '热情的', '激发购买欲的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:36:46+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'nian',
    display_name_ko: '이안',
    display_name_ja: 'イアン',
    display_name_en: 'Ian',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '이 아이템과 함께라면 사랑받는 남자친구, 어렵지 않아요.',
    },
    tags_ko: ['활기찬', '싹싹한', '열정적인', '구매유발하는', '풍부한'],
    tags_ja: [
      '活気のある',
      '気さくな',
      '情熱的な',
      '購買意欲をそそる',
      '響きの豊かな',
    ],
    tags_en: ['energetic', 'affable', 'passionate', 'pitchable', 'rich'],
    tags_zh: ['有活力的', '善解人意的', '热情的', '激发购买欲的', '丰富的'],
    engine: 'NES',
    serviced_at: '2023-04-20T18:36:34+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vdonghyun',
    display_name_ko: '동현',
    display_name_ja: 'ドンヒョン',
    display_name_en: 'Donghyun',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '집에서 포장마차 감성으로 오뎅 한 접시 어떠세요?',
    },
    tags_ko: ['신뢰가는', '활기찬', '싹싹한', '열정적인', '구매유발하는'],
    tags_ja: [
      '信頼感を与える',
      '活気のある',
      '気さくな',
      '情熱的な',
      '購買意欲をそそる',
    ],
    tags_en: ['trustworthy', 'energetic', 'affable', 'passionate', 'pitchable'],
    tags_zh: ['可靠的', '有活力的', '善解人意的', '热情的', '激发购买欲的'],
    engine: 'NEUVIS',
    serviced_at: '2023-04-20T19:03:33+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vian',
    display_name_ko: '이안',
    display_name_ja: 'イアン',
    display_name_en: 'Ian',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '이 아이템과 함께라면 사랑받는 남자친구, 어렵지 않아요.',
    },
    tags_ko: ['활기찬', '싹싹한', '열정적인', '구매유발하는', '풍부한'],
    tags_ja: [
      '活気のある',
      '気さくな',
      '情熱的な',
      '購買意欲をそそる',
      '響きの豊かな',
    ],
    tags_en: ['energetic', 'affable', 'passionate', 'pitchable', 'rich'],
    tags_zh: ['有�力的', '善解人意的', '热情的', '激发购买欲的', '丰富的'],
    engine: 'NEUVIS',
    serviced_at: '2023-04-20T19:03:28+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'ngyeongjun',
    display_name_ko: '경준',
    display_name_ja: 'ギョンジュン',
    display_name_en: 'Gyeongjun',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '앗, 설마 제 이름을 잊어버리신 건 아니겠죠?',
    },
    tags_ko: ['신뢰가는', '싹싹한', '친절한', '감미로운'],
    tags_ja: ['信頼感を与える', '気さくな', '親切な', 'とろけるような'],
    tags_en: ['trustworthy', 'affable', 'kind', 'mellow'],
    tags_zh: ['可靠的', '善解人意的', '亲切的', '美妙的'],
    engine: 'NES',
    serviced_at: '2023-11-09T20:22:06+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'ndaeseong',
    display_name_ko: '대성',
    display_name_ja: 'デソン',
    display_name_en: 'Daeseong',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '밤하늘에 빛나는 별처럼, 당신의 내일도 반짝이길 바랄게요.',
    },
    tags_ko: ['신뢰가는', '차분한', '매력적인', '친절한', '감미로운'],
    tags_ja: [
      '信頼感を与える',
      '落ち着いた',
      '魅力的な',
      '親切な',
      'とろけるような',
    ],
    tags_en: ['trustworthy', 'calm', 'charming', 'kind', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '有魅力的', '亲切的', '美妙的'],
    engine: 'NES',
    serviced_at: '2023-11-09T20:22:11+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'njonghyeok',
    display_name_ko: '종혁',
    display_name_ja: 'ジョンヒョク',
    display_name_en: 'Jonghyeok',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': 'PC를 재부팅해보시겠어요?',
    },
    tags_ko: ['싹싹한', '친근한', '풍부한', '호기심많은'],
    tags_ja: ['気さくな', 'フレンドリーな', '響きの豊かな', '好奇心旺盛な'],
    tags_en: ['affable', 'friendly', 'rich', 'curious'],
    tags_zh: ['善解人意的', '和蔼的', '丰富的', '好奇心旺盛的'],
    engine: 'NES',
    serviced_at: '2023-11-09T20:22:21+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: false,
      'emotion-strength': false,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vgoeun',
    display_name_ko: '고은',
    display_name_ja: 'コウン',
    display_name_en: 'Koeun',
    gender: 'F',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '오늘의 첫 곡은 비발디의 사계입니다.',
      '1': '다시는 너를 만날 수 없단 사실이 날 슬프게 해.',
      '2': '오늘 이 자리에 있는 분들, 모두 행복했으면 좋겠어요.',
      '3': '당신의 저의가 그렇다면 저도 가만히 있을 수 없어요.',
    },
    tags_ko: ['차분한', '친절한', '감미로운', '설레는'],
    tags_ja: ['落ち着いた', '親切な', 'とろけるような', 'わくわくする'],
    tags_en: ['calm', 'kind', 'mellow', 'heart-throbbing'],
    tags_zh: ['冷静的', '亲切的', '美妙的', '令人心动的'],
    engine: 'NEUVIS',
    serviced_at: '2023-11-09T20:38:20+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: true,
      'emotion-strength': true,
      'end-pitch': false,
    },
  },
  {
    speaker: 'vdaeseong',
    display_name_ko: '대성',
    display_name_ja: 'デソン',
    display_name_en: 'Daeseong',
    gender: 'M',
    lang: 'ko',
    age_group: 'youth',
    default_text: {
      '0': '밤하늘에 빛나는 별처럼, 당신의 내일도 반짝이길 바랄게요.',
      '1': '내 슬픔이 모두의 슬픔이 아닌 건 알아.',
      '2': '이번에 산 주식이 상한가를 치면서 아주 큰 수익을 올렸지.',
      '3': '이런걸로 우리한테 뭐라 하시면 어떡합니까?',
    },
    tags_ko: ['신뢰가는', '차분한', '매력적인', '친절한', '감미로운'],
    tags_ja: [
      '信頼感を与える',
      '落ち着いた',
      '魅力的な',
      '親切な',
      'とろけるような',
    ],
    tags_en: ['trustworthy', 'calm', 'charming', 'kind', 'mellow'],
    tags_zh: ['可靠的', '冷静的', '有魅力的', '亲切的', '美妙的'],
    engine: 'NEUVIS',
    serviced_at: '2023-11-09T20:38:25+09:00',
    modulate: {
      speed: true,
      volume: true,
      pitch: true,
      alpha: true,
      emotion: true,
      'emotion-strength': true,
      'end-pitch': false,
    },
  },
];
